## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(n3B4vW0wPXgGWM3kdWa4WA==)     #upms
      client-secret: ENC(n3B4vW0wPXgGWM3kdWa4WA==) #upms
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
        - '/user/info/*'
        - '/social/info/*'
        - '/mobile/*'
        - '/log/save'

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xing1618
    url: jdbc:mysql://xing-mysql:3306/xing?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

# swagger相关配置,覆盖全局配置
swagger:
  authorization:
    authorization-scope-list:
      - scope: 'server'
        description: 'server all'
      - scope: 'read'
        description: 'read all'
      - scope: 'write'
        description: 'access all'
# Logger Config
logging:
  level:
    com.pig4cloud.pigx.admin.mapper: debug
