## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(6MfY3gdvgfVWp2ZnbcBtHA==)     #gen
      client-secret: ENC(6MfY3gdvgfVWp2ZnbcBtHA==) #gen
      scope: server
# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xing1618
    url: jdbc:mysql://xing-mysql:3306/xing?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  resources:
    static-locations: classpath:/static/,classpath:/views/
