## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(WIBftE9x48b4f75NScwEAA==)     #daemon
      client-secret: ENC(WIBftE9x48b4f75NScwEAA==) #daemon
      scope: server
## 定时任务
spring:
  # 保存定时任务的数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xing1618
    url: jdbc:mysql://xing-mysql:3306/xing?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  elasticjob:
    # 分布式任务协调依赖zookeeper
    zookeeper:
      server-lists: xing-zookeeper:2181
      namespace: xing-daemon
    # 普通任务
    simples:
      spring-simple-job:
        job-class: com.xing.daemon.job.PigxSimpleJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.xing.daemon.listener.PigxElasticJobListener
      spring-simple-job2:
        job-class: com.xing.daemon.job.PigxSimpleJob2
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.xing.daemon.listener.PigxElasticJobListener
    # 简单任务
    dataflows:
      spring-dataflow-job:
        job-class: com.xing.daemon.job.PigxDataflowJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        streaming-process: true
        eventTraceRdbDataSource: 'dataSource'
        listener:
          distributed-listener-class: com.xing.daemon.listener.PigxDistributeElasticJobListener
          started-timeout-milliseconds: 5000
          completed-timeout-milliseconds: 10000
