spring:
  cloud:
    gateway:
      locator:
        enabled: true

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'xingxingxingxing'

# 不校验验证码终端
ignore:
  clients:
    - test
  swagger-providers:
    - xing-auth
    - xing-tx-manager
